import type { Metadata } from "next";
import { Inter, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
// import {  } from "next/font/google"

const inter = Inter({ subsets: ["latin"] });

const Bricolage_Grotesque_init = Bricolage_Grotesque({
  subsets:['latin'],
  // weight:['700', '400'], 
  variable:'--font-Bricolage_Grotesque'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${Bricolage_Grotesque_init.className}`}>{children}</body>
    </html>
  );
}
